export default interface ICard {

    cardPercentProgress: number,
    currentSwimId: number,
    childPercentProgress: number,
    ExternalCardId: string,
    currentQueue: string,
    isRelated: boolean,
    currentOwner: number,
    modifiedBy: string,
    currentQueueId: number,
    id: number,
    currentSwimName: string,
    currentOwner_userId: number,
    estimates: number,
    workspaceId: number,
    classOfService: string,
    backlogPos: number,
    summaryType: string,
    priority: string,
    cardSize: string,
    workspaceType: string,
    createdDate: Date,
    createdBy: string,
    dateIdentified: Date,
    name: string,
    workType: string,
    modifiedDate: Date,
    numeric3: number,
    numeric2: number,
    numeric1: number,
    smartLane: string,
    currentState: string,
    cardNumber: string
}